title: CSS Reference
subtitle: "A free visual guide to CSS"
description: "CSS Reference is a free visual guide to CSS. It features the most popular properties, and explains them with illustrated and animated examples."
share: "CSS Reference: a free visual guide to the most popular CSS properties."
url: https://cssreference.io
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
